/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: d0cf941735fa1f56018103f01327da18)
interface __BaseEnv_Env {
	APP_ENV: "prod" | "dev";
	CLASHKING_API_BASE_URL: "https://api.clashk.ing";
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_BOT_TOKEN: string;
	CLASHKING_API_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProdEnv {
		APP_ENV: "prod";
		CLASHKING_API_BASE_URL: "https://api.clashk.ing";
		DISCORD_APPLICATION_ID: string;
		DISCORD_PUBLIC_KEY: string;
		DISCORD_BOT_TOKEN: string;
		CLASHKING_API_TOKEN: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "CLASHKING_API_BASE_URL" | "DISCORD_APPLICATION_ID" | "DISCORD_PUBLIC_KEY" | "DISCORD_BOT_TOKEN" | "CLASHKING_API_TOKEN">> {}
}
