name: Codespell Check

on:
  workflow_call:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell

      - name: Run codespell
        run: codespell
