name: Image Builder

on:
  workflow_dispatch:
    # Allow manual builds for master branch only
    inputs:
      branch:
        description: 'Branch to build'
        default: 'master'
  push:
    branches-ignore:
      - master # Exclude master branch from auto-builds

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'master' ||
      github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/clashkinginc/clashkingbot:latest${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache