name: Image Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }} # Automatically checkout the triggering branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Sanitize branch name
        id: sanitize
        run: echo "SANITIZED_BRANCH=$(echo '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9_.-]/-/g')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/clashkinginc/clashkingbot:${{ github.ref_name == 'master' && 'latest' || env.SANITIZED_BRANCH }}