name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      contains_build: ${{ steps.check.outputs.contains_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if commit message contains 'build:'
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"build:"* ]]; then
            echo "::set-output name=contains_build::true"
          else
            echo "::set-output name=contains_build::false"
          fi

  codespell-check:
    needs: check-commit-message
    if: needs.check-commit-message.outputs.contains_build == 'true'
    uses: ./.github/workflows/codespell.yml

  docker-build:
    needs: [check-commit-message, codespell-check]
    if: needs.check-commit-message.outputs.contains_build == 'true'
    uses: ./.github/workflows/docker.yml
